from __future__ import annotations


def generate_readme(
    bundle_name: str,
    recording_ids: tuple[str, ...],
    mode: str,  # "single" | "multi" | "timeslice" | "cross_stream"
    time_range_ns: tuple[int, int] | None,
    stream_keys: tuple[str, ...],
    has_annotations: bool,
    has_recording_metadata: bool,
) -> str:
    recording_ids_joined = ", ".join(recording_ids)

    time_range_line = (
        f"- **Time Range**: {time_range_ns[0]} ns — {time_range_ns[1]} ns"
        if time_range_ns is not None
        else ""
    )

    annotations_line = (
        "├── annotations/          # Marker and segment CSV files" if has_annotations else ""
    )
    recording_metadata_line = (
        "├── recording_metadata/   # Recording metadata JSON files"
        if has_recording_metadata
        else ""
    )

    stream_list = "\n".join(f"- `{key}`" for key in stream_keys) if stream_keys else "*(none)*"

    # Build directory structure lines, filtering out empty lines
    dir_lines = [
        f"{bundle_name}/",
        "├── manifest.json          # Export metadata",
        "├── README.md              # This file",
        "├── streams/               # Stream data files",
    ]
    if annotations_line:
        dir_lines.append(annotations_line)
    if recording_metadata_line:
        dir_lines.append(recording_metadata_line)
    dir_structure = "\n".join(dir_lines)

    # Build contents section lines, filtering empty
    contents_lines = [
        f"- **Mode**: {mode}",
        f"- **Recording(s)**: {recording_ids_joined}",
    ]
    if time_range_line:
        contents_lines.append(time_range_line)
    contents_block = "\n".join(contents_lines)

    return f"""\
# Export Bundle: {bundle_name}

## Contents

{contents_block}

## Directory Structure

```
{dir_structure}
```

## Streams Exported

{stream_list}

## Quick Start

```python
import numpy as np
import pandas as pd
from pathlib import Path

bundle = Path("{bundle_name}")

# Load signal CSV
df = pd.read_csv(bundle / "streams" / "signal.csv")

# Load NPZ
data = np.load(bundle / "streams" / "signal.npz")
```

---
*Generated by ModLink Studio export system*
"""
